<?php

namespace App\Models;

use App\Models\Scopes\ConversationScope;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Conversation extends Model
{
    use HasFactory;
    use CrudTrait;

    protected $guarded = ["id"];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ConversationScope);
    }

    public function Users()
    {
        return $this->belongsToMany(User::class, "conversation_user", "conversation_id", "user_id");
    }

    public function Chats(): HasMany
    {
        return $this->hasMany(Chat::class, "conversation_id", "id")->orderBy("created_at", "ASC");
    }
}
