<?php

namespace App\Models;

use App\Models\Scopes\BusinessScope;
use App\Models\Scopes\StaffScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Staff extends User
{
    use HasFactory;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
//        static::addGlobalScope(new BusinessScope);
        static::addGlobalScope(new StaffScope);
    }

    public function setRoleAttribute()
    {
        $this->attributes["role"] = "staff";
    }

    public function Grades()
    {
        return $this->belongsToMany(Grade::class, "staff_grade", "staff_id", "grade_id");
    }

    public function setPasswordAttribute($value)
    {
        parent::setPasswordAttribute($value); // TODO: Change the autogenerated stub
    }

}
